### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'open_sftp'

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#469]
In GitLab by @pablohe on Jan 22, 2020, 20:01

Hi 

`autosubmit run t01q` works in 12.0 version and fail with this error in 12.1

```
[ERROR] local submission failed due to Unknown error
[CRITICAL] Unhandled exception on Autosubmit: 'NoneType' object has no attribute 'open_sftp'
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 440, in parse_args
    return Autosubmit.run_experiment(args.expid, args.notransitive,args.update_version)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 1252, in run_experiment
    if Autosubmit.submit_ready_jobs(as_conf, job_list, platforms_to_test, packages_persistence,hold=False):
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/autosubmit.py", line 1320, in submit_ready_jobs
    package.submit(as_conf, job_list.parameters, inspect, hold=hold)
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_packages.py", line 109, in submit
    self._send_files()
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/job/job_packages.py", line 139, in _send_files
    self.platform.send_file(self._job_scripts[job.name])
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/platforms/locplatform.py", line 104, in send_file
    self.check_remote_log_dir()
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 670, in check_remote_log_dir
    self.restore_conection()
  File "/shared/earth/software/autosubmit/3.12.1b-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.12.1b0-py2.7.egg/autosubmit/platforms/paramiko_platform.py", line 71, in restore_conection
    self._ftpChannel = self._ssh.open_sftp()
AttributeError: 'NoneType' object has no attribute 'open_sftp'
```

**Comment by kinow** [comment]
In GitLab by @pablohe on Jan 22, 2020, 20:02

mentioned in issue auto-ecearth3#1151

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 23, 2020, 08:57

Hi @pablohe,

I did a refactor of the reconnection mechanic if the first login specified in host = mn1.bsc.es, fails.

Its weird that this bug is happening due I tested with 3 different experiments but I'll solve it asap.

Edit: still working fine with my experiments.. I'll copy your config

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Jan 23, 2020, 10:04

hi @pablohe , 

Could you test again with any of the test exp? I made changes to the code and I'm not getting the error, I guess the issue is when it tries to send files since the only difference is that I used templates only with sleep 8s. 

Also, the log now indicates which platform fails and some tips.

**Comment by kinow** [comment]
In GitLab by @pablohe on Jan 23, 2020, 10:58

closed

**Comment by kinow** [comment]
In GitLab by @pablohe on Jan 23, 2020, 10:58

reopened
