### ISSUE TITLE
refresh does not work in 3.7.5

### ISSUE THREAD

**Issue by kinow** [BSC-ES/autosubmit#211]
In GitLab by @dmanubens on Nov 10, 2016, 20:52

```
dmanuben@ bscearth309:~/pyCharm/autosubmit/bin> ./autosubmit refresh a010
[CRITICAL] Unhandled exception on Autosubmit: AutosubmitConfig instance has no attribute '_exp_parser'
Traceback (most recent call last):
  File "/home/Earth/dmanuben/pyCharm/autosubmit/autosubmit/autosubmit.py", line 361, in parse_args
    return Autosubmit.refresh(args.expid, args.model_conf, args.jobs_conf)
  File "/home/Earth/dmanuben/pyCharm/autosubmit/autosubmit/autosubmit.py", line 1451, in refresh
    if not as_conf.check_expdef_conf():
  File "/home/Earth/dmanuben/pyCharm/autosubmit/autosubmit/config/config_common.py", line 341, in check_expdef_conf
    parser = self._exp_parser
AttributeError: AutosubmitConfig instance has no attribute '_exp_parser'
```

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Nov 17, 2016, 16:57

Mentioned in commit 5872fb973830ee7654e76a480de4cc47d65295a4

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Nov 25, 2016, 17:15

Status changed to closed by commit 5872fb973830ee7654e76a480de4cc47d65295a4

**Comment by kinow** [comment]
In GitLab by @ jlope2 on Dec 23, 2016, 16:45

Milestone removed
